ListBaseStack.o:ListBaseStack.h ListBaseStack.c
	gcc -c ListBaseStack.c

ListBaseStackMain.o: ListBaseStack.h ListBaseStackMain.c
	gcc -c ListBaseStackMain.c

main: ListBaseStack.o ListBaseStackMain.o
	gcc ListBaseStack.o ListBaseStackMain.o -o main